"""add draft_source to Campaign

Revision ID: 3525e546a959
Revises: 8e26b530d937
Create Date: 2026-08-14 11:13:40.918354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3525e546a959'
down_revision: Union[str, None] = '8e26b530d937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('draft_source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'draft_source')
    # ### end Alembic commands ###
